### ISSUE TITLE
charge_energy_added sensor is using SensorStateClass.TOTAL instead of TOTAL_INCREASING

### ISSUE THREAD

**Issue by claplace** [jhansche/ha-teslafi#44] opened 2024-07-11 01:03 UTC
The `charge_energy_added` sensor gets reset to `0` each time a new charging session starts, and I observed in my energy dashboard that this was recorded as a huge negative. I found commit https://github.com/jhansche/ha-teslafi/commit/2bdd838771fbab9155a54b2154bd6dcd68462cab that changed the sensor state class from `TOTAL_INCREASING` to `TOTAL`, without much explanation.

I started a discussion on that commit. There are a few comments there that I don't want to copy paste here, but here's some bits from the documentation as quoted by @jhansche:

> Guidance from [the](https://developers.home-assistant.io/docs/core/entity/sensor#available-state-classes) [docs](https://developers.home-assistant.io/docs/core/entity/sensor#how-to-choose-state_class-and-last_reset) is to always prefer total unless that does not work. However, it also states
>>The sensor's value may reset to 0, and its value can only increase: state class total_increasing. Examples: energy consumption aligned with a billing cycle, e.g. monthly, an energy meter resetting to 0 every time it's disconnected.

> The documentation goes on to say:
>>It is important that the integration ensures that the value cannot erroneously decrease in the case of calculating a value from a sensor with measurement noise present. There is some tolerance, a decrease between state changes of < 10% will not trigger a new meter cycle.

For now I'm customizing (didn't know it was possible!) my sensor using this snippet:

```# customize.yaml
sensor.<carName>_energy_added:
  state_class: total_increasing```

**Comment by jhansche** [comment] 2024-07-12 23:08
Following up on the issues described in the commit comments linked above: I also added the override to total_increasing like suggested, and I can confirm that TeslaFi sometimes reports a slightly lower value, which still gets reported as a negative in the energy panel: 
![Screenshot_20240712-185159](https://github.com/user-attachments/assets/6af3397e-9628-401f-8275-a564a8275f5c)
![Screenshot_20240712-183238](https://github.com/user-attachments/assets/e89abf59-e7aa-4b17-9c23-85998412e18c)

However, with total_increasing, as long as the decrease is less than 10%, it at least doesn't treat it as a huge negative value when it resets to 0, which is what the original issue is reporting: 
![Screenshot_20240712-185336](https://github.com/user-attachments/assets/0f91aff8-2f1e-4f1e-8258-96de5f437240)

To explain, these graphs aren't showing the same scale. The first energy graph is the current day, second energy graph is yesterday; and the energy_added graph is the past 24h. So they don't quite line up, but that should give you an idea of how they would line up. For comparison, see the graph in the original commit comments, where that energy_added reset to 0 would have been shown in the energy graph as a large negative. 

I'll have to keep testing to see if a reported value that is more than 10% lower than the last value would result in a large overflow: i.e. going from 2.5 kWh to 2.0 kWh previously would show up as `-0.5`, but under total_increasing that would be displayed as `+2.0`, which I think is wrong.

But I may also just be thinking of it wrong, because it might be resetting energy_added any time it remains plugged in but stopped charging. If that's the case I might want to change the availability condition -- currently that is checking the `is_plugged_in` property, but maybe it's more accurate to check `is_charging`.

**Comment by claplace** [comment] 2024-07-13 14:56
I found this TeslaFi KB article [[How is kWh used and added calculated?](https://support.teslafi.com/knowledge-bases/2/articles/11-how-is-kwh-used-and-added-calculated)](https://support.teslafi.com/knowledge-bases/2/articles/11-how-is-kwh-used-and-added-calculated):

> kWh added is obtained directly from the TeslaFi API. It is calculated by the difference between the starting energy_added field and the ending energy_added field of the charging session.

I think there is a typo, and it should read "Tesla API", otherwise it does not make sense.

I understand there that the `energy_added` is coming from the Tesla API, with an offset from TeslaFi to zero-it when a charge starts.

> But I may also just be thinking of it wrong, because it might be resetting energy_added any time it remains plugged in but stopped charging.

[2024-07-11 Charge Details.pdf](https://github.com/user-attachments/files/16202550/2024-07-11.Charge.Details.pdf)

I did an experiment the other day at a free charger. I've setup the charge limit lower to force the charging session to stop and get the vehicle to sleep. At first I forgot that Sentry mode was enabled, but once disabled the car did enter sleep. When I woke it up and increased the charge limit, the charging session restarted, and the `energy_added` was not reset. I think that answers your question. Of course it's only a sample of 1...

One weird thing on the data above is that after the first charge session complete, with no power delivered to the car, the `energy_added` continued to increase up to +0.5kWh.

At the end of the second charging session, I remotely stopped the charge (notice the "Stopped" vs "Complete" state), and turned on AC for a few minutes. That seems to have caused `energy_added` to decrease. I will have to reproduce it, but that would mean that the value is not monotonic, and is updated as long as the vehicle is plugged in, charging or not charging.

**Comment by claplace** [comment] 2024-07-13 19:27
Two more experiments :-)

I plugged my car to the $$ public L2 charger, without starting the charge. The `energy_added` was reset to 0, even if the charging state only went from **Disconnected** to **NoPower**.

<img width="506" alt="Screenshot 2024-07-13 at 15 18 32" src="https://github.com/user-attachments/assets/906e6564-c742-4720-aee8-44efdaabd32f">

I also put the A/C to the max and all seats heating. Battery range went down a little bit as a lot of power was used to heat the seats and cool the cabin... I'll also note that the `energy_added` value stayed at 0... more on that later.

**Comment by claplace** [comment] 2024-07-13 19:41
On the second experiment, I plugged the charger, started the charge, and limited the charging current to 5A. At 208 V that makes only about 1 kW.

First with full AC and seats heater on. `energy_added` stays at 0, as well as the `charge_rate`.  Then I stopped the AC/heater, increased the charging current, and the `charge_rate` went up to **23.5** (mi/h?). And only a couple of minutes after the `energy_added` went above zero.

I let it charge for 1kWh (as the car screen was showing), and turned the charging current back to 5A, and started AC/heaters again. And as I was thinking the `charge_rate` went to 0 again, and the `energy_added` value started decreasing. After some time both the TeslaFi numbers and the on-screen display showed **+0kWh**!

<img width="611" alt="Screenshot 2024-07-13 at 15 23 35" src="https://github.com/user-attachments/assets/6e1145ed-41c1-46b1-bec8-c3027c1780a7">

Funny thing, the TeslaFi summary shows a `- kWh` added value:

<img width="1003" alt="Screenshot 2024-07-13 at 15 37 37" src="https://github.com/user-attachments/assets/2559235d-92d1-4d37-b28c-5248f8774f2c">

A quick screenshot from home assistant:

![image](https://github.com/user-attachments/assets/3aef1ef8-3423-4e1b-a847-a313f824c3b5)

Now I believe that the `energy_added` value from TeslaFi comes directly from Tesla. It goes up and down depending on the HV battery consumption when the charger is plugged. It can even become negative, but is "capped" at 0 by Tesla (as well as the `charge_rate`, never shown negative).

**Comment by claplace** [comment] 2024-07-13 19:52
Just like TeslaFi computes the "Energy used" by multiplying charger current and voltage, I think a template sensor doing the same is the only way to get a true energy meter for what the car consumed.

"Energy added" is for the HV pack, and can't even be relied onto because it is never shown negative, i.e. when pre-conditioning.

On you down hooks, can you "zoom in" or get the TeslaFi data for that period? A 2kWh drop could come from pre-conditioning.

**Comment by claplace** [comment] 2024-07-13 20:20
A couple of graphes to compare the `energy_added` with what a "energy used" would be. First in kWh total energy, and then in instant kW power:

<img width="510" alt="Screenshot 2024-07-13 at 16 14 51" src="https://github.com/user-attachments/assets/59683d6b-d49d-4ef3-8566-c4068370d652">
<img width="507" alt="Screenshot 2024-07-13 at 16 18 53" src="https://github.com/user-attachments/assets/bc596001-63ee-424e-bcbf-60cf0ff6666c">

Full A/C + seat heaters used up to 9 kW!!!

**Comment by claplace** [comment] 2024-07-13 20:25
with a 3 minutes rolling average:

<img width="497" alt="image" src="https://github.com/user-attachments/assets/ee390ae4-5ad7-47d4-a521-b54b612b0d4a">

**Comment by jhansche** [comment] 2024-07-13 20:38
> On you down hooks, can you "zoom in" or get the TeslaFi data for that period? A 2kWh drop could come from pre-conditioning.

My screenshots of TeslaFi in the [commit comments](https://github.com/jhansche/ha-teslafi/commit/2bdd838771fbab9155a54b2154bd6dcd68462cab#commitcomment-144104802) is showing that same Jul 3 "hook" period that was in my original graph. It didn't drop according to TeslaFi.

---

At any rate it sounds like what you're describing is that we **cannot** using total_increasing after all.

However, maybe we can set the `last_reset` timestamp when it goes from unplugged to plugged in, or goes from a sufficiently-non-zero number to a close-to-zero number. That would allow for the energy rate to be either positive or negative (which are real and valid possibilities according to your tests), but when a new charging session is beginning, the reset timestamp will cause it to ignore the large reset back to 0 and won't consider it a large negative.

**Comment by claplace** [comment] 2024-07-13 20:57
I agree `total_increasing` cannot be used.

For `last_reset`, the "new charging session" could be set when the charging state changes from `Disconnected` to anything else (and not just switching to `Charging` as e.g. going to sleep does not reset the `energy_added` value).

Wow, I had not imagined that this negative spike would lead to this amount of tests and discussion. Thank you very much for your work, I love the integration!

**Comment by claplace** [comment] 2024-07-13 20:59
> My screenshots of TeslaFi in the [commit comments](https://github.com/jhansche/ha-teslafi/commit/2bdd838771fbab9155a54b2154bd6dcd68462cab#commitcomment-144104802) is showing that same Jul 3 "hook" period that was in my original graph. It didn't drop according to TeslaFi.

Ah, I got tricked again looking at the bottom for the "most recent" values. Indeed, the charger was disconnected at 5.11kWh, no preconditioning possible there. Still a mystery!

**Comment by jhansche** [comment] 2024-07-21 19:29
So, I've started a draft PR #46 for this. It detects a change in `is_plugged_in` status (from unplugged to plugged), OR a change in `chargeNumber` as reported by TeslaFi, and uses that to set the `last_reset` time to the time reported by TeslaFi. From what I can tell, that is working properly, but I haven't thoroughly tested it yet.

If you want to test it using HACS, you can use the `update.install` service to install the `pr/reset-energy` version. That requires enabling experimental features in HACS. I will be testing this myself over the next week or so, just to validate that it solves _that_ part of the problem.

---

However, as I'm thinking of this more, it brings me to a conceptual dilemma, relating to the Energy dashboard. Let's take a smart plug as an example, which is monitoring the power to a device (let's say a Fan or whatever). The purpose of adding that to the dashboard is to see what amount of energy the Fan is consuming. If that energy goes negative, it means the Fan is putting power back into the grid, which we know is not actually how the Fan works.

Based on your earlier tests, it appears that the `energy_added` measurement is essentially measuring how much (net) energy has been added to the car's battery. On the surface, you would think that means means how much energy from your power source has been transmitted into the car's battery, in order to charge the battery. However, if you turn on climate or have sentry mode enabled or what have you, that measurement could drop: one minute you've added 5.0 kWh, and a few minutes later, it reports 4.0 kWh, because there was a net-decrease in the amount of energy that went into the battery. Don't focus too much on the exact numbers, just thinking of it conceptually.

If you add that to your energy dashboard, that drop would be reported as a `-1 kWh` change, which the energy dashboard interprets to mean that 1 kWh went **from the car, back into the grid**, which we know to be false. When in reality, the correct measure of energy consumption would be how much power has _flowed through_ the mobile charger (or wall charger, or whatever). That extra 1+ kWh still came from the grid and went through the charger - it just didn't go into the battery (or the battery consumed more than what was added).

I guess what I'm pointing out is that you're trying to treat the fluctuating energy differential of the battery's level, as a measure of energy consumption, but it's not.

However, all that being said, the `last_reset` change does still appear to be the correct thing to do - regardless of what you do with that entity. If you choose to add it to your energy dashboard, the `last_reset` change will at least prevent the large drop that happens when your last charging session's value resets to 0. I just have to point out that treating it as an "[Individual Device](https://next.home-assistant.io/docs/energy/individual-devices/)" is misleading due to this expected fluctuation due to the entity representing net-energy (that flowing into the battery, **minus** whatever flows out of the battery at the same time, to run other systems in the car).

Instead, I believe the _correct_ way to track this total energy flowing through the car charger itself, is with the integral helper like described at that link^, using the `charger_power` (W) and/or `charger_apparent_power` (VA) as the input. Otherwise you could have some other energy-sensing device on the input power source to the charger. I know you said you don't charge at home, so that doesn't actually apply in your case. But by the same logic: the amount of energy flowing into your car also doesn't apply to your home's energy usage either. In other words, I think adding it to the Energy dashboard as an individual device is not the right use of the entity or of the energy dashboard.

But I still agree that we should set the `last_reset` attribute correctly anyway. And with that out of the way, you're free to configure your HA however you'd like 😉

**Comment by claplace** [comment] 2024-07-23 12:53
Hi! Yes I agree that the `energy_added` entity is not fit for the energy dashboard, and that an integral helper is the only way to get an estimate of the power used, just as TeslaFi does for themselves.

I started playing with it:

```
sensor:
  - platform: integration
    source: sensor.baybaycrow_charger_power
    name: baybaycrow_energy_used
    unique_id: baybaycrow_energy_used
    round: 2
    max_sub_interval:
      minutes: 5
```

with the first 2 charges:

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/390c0009-b6e3-484d-99e5-c2b7802602f1">

And it looks great in the energy dashboard:

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/3f6a9149-bca1-4cf5-a4d8-f3219db5d3a7">

Also dwarfing the other power consumption devices lol.

I wonder if it could be made part of the component.

**Comment by jhansche** [comment] 2024-07-23 20:45
FWIW, simply using `total_increasing` (from customize.yaml as suggested in the commit comments), or using my PR branch with `last_reset`, also provides a much more meaningful appearance in the energy graph -- with the caveats noted above. In this case, ~Jul 10 is when I first made the `total_increasing` change in customize.yaml, and Jul 21 is when I started testing the `last_reset` PR:

![Screenshot 2024-07-23 at 4 36 17 PM](https://github.com/user-attachments/assets/6ca5f938-966d-4e73-99f9-2bd6224b3ed6)

So, I mention that because I don't think that the integral total is vital for resolving this issue. The distinction of some (likely small) portion of `energy_added` potentially being lost to additional battery usage while plugged in, doesn't seem important enough for this integration to be the one to keep track of it.

I also don't think it should be on any integration to reimplement the riemann sum (integral). That existing helper is the official documented way to convert a Power entity into an Energy entity, and we shouldn't deviate from that here by recreating it ourselves.

**Comment by claplace** [comment] 2024-07-24 01:06
I removed my customization and updated the teslafi component to the branch version. I do believe the `last_reset` is the correct fix for `energy_added`.

I also agree that reimplementing the riemann sum is not a good idea. I thought that maybe there was a possibility to have a new sensor included in the component (maybe even disabled by default?), but still using the builtin integral helper. But that's not this PR.

Does the `last_reset` fix the "hooks down" on the `energy_added` graph you had?

**Comment by jhansche** [comment] 2024-07-24 03:30
Good question. No it looks like it did not fix that: 

![Screenshot_20240723-230246](https://github.com/user-attachments/assets/e3e6a46e-b694-48fb-868d-d357e5db357b)

But I guess I wouldn't expect it to either, because it's only sets last_reset when it goes from unplugged to plugged in (or the charge session number changes to a different non-zero number). When the charger is unplugged, we don't set last_reset because TeslaFi is still showing a non-zero energy_added. But when it's unplugged, we do mark it unavailable. If I had to guess, I expect that the HA statistics recorder is averaging the time series at the point where it goes from the last known energy_added value to unavailable, and may be treating unavailable as 0, so it projects that as a decline, aligned to the time series. 

I'll dig into the values that made it into the DB and see if I can prove that. It could be that we need to also set last_reset when the charger is unplugged; but I'd be worried that the lingering energy_added that TeslaFi continues to report after unplugging could later resurface and then we'll have the opposite problem: a large jump as it goes from what it thinks should have been 0, back up to the last reported energy_added... 🤔  But as long as it continues to report unavailable, we'll be ignoring the TeslaFi value, and then when it's plugged back in it'll be reset again. I think triggering last_reset when it's unplugged would cause the recorder to "skip" that transitioning measurement, and would prevent the strange drop that's caused by the time series averaging.

Another option could be to keep last_reset as it is, but remove the unavailable status. That would cause energy_added to remain at the plateau when the charger was unplugged, and only reset to 0 when it's plugged back in. I don't like that, because it means we're reporting a value that is no longer valid (that's why I set it unavailable in the first place while unplugged)

For posterity, I continued to see the hook downward even between Jul 10-20, when it was using the total_increasing override: 

![Screenshot_20240723-232202](https://github.com/user-attachments/assets/758e6d04-23e8-4952-8299-e0a7d48f7a00)

**Closed** 2024-08-03 12:29 UTC
