### ISSUE TITLE
No connection?

### ISSUE THREAD

**Issue by loop2** [jhansche/ha-teslafi#14] opened 2023-12-12 14:09 UTC
Hi from two days I have installed this integration but I have for the most of the time unknown or not available indication on all entities of the diagnostic section. Teslafi connection is correct and see the car. 
Thanks

**Comment by jhansche** [comment] 2023-12-12 14:15
It's working for me. Can you filter your logs to the integration, and look for any errors? Go to Settings > System > Logs, and search `teslafi`.

Have you confirmed that the teslafi API is working with your token? Do that by first logging in to teslafi, and then go to https://teslafi.com/api.php (it will redirect you if you're not logged in, so make sure you're logged in first), and click the link at the bottom of the "API Token" page.

**Comment by loop2** [comment] 2023-12-12 14:18
`Logger: homeassistant
Source: custom_components/teslafi/device_tracker.py:46
Integration: TeslaFi ([documentation](https://github.com/jhansche/ha-teslafi/blob/main/README.md), [issues](https://github.com/jhansche/ha-teslafi/issues))
First occurred: 14:50:47 (9 occurrences)
Last logged: 15:14:46

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/teslafi/device_tracker.py", line 46, in extra_state_attributes
    int(h)
ValueError: invalid literal for int() with base 10: '' `

**Comment by jhansche** [comment] 2023-12-12 14:53
This was reported in #11, and resolved in `main`.

Looks like that wasn't released yet though, so you would have to install it from the main branch, rather than `v2.1`. I'll release a new version soon.

**Comment by jhansche** [comment] 2023-12-12 15:19
Released [v2.2](https://github.com/jhansche/ha-teslafi/releases/tag/v2.2).

**Closed by jhansche** 2023-12-12 15:19 UTC
