### ISSUE TITLE
Multiple cars info combined into one device

### ISSUE THREAD

**Issue by LampyDave** [jhansche/ha-teslafi#4] opened 2023-09-27 21:07 UTC
Very many thanks for your work on this - I trust the TeslaFi service to not keep the car 'awake' so prefer not to connect directly.

I have access to two different TeslaFi accounts and would like to add them both to my HA. When I add the second API token it recognises it successfully and asks which area to add this second car to. However, it then combines both cars into one 'device', so instead of 2 devices with 40 entities each I then have 1 device with 80 entities, all in the second car's area.

In the dashboard there are then two different entries, named the same thing (all named as the second account) but actually referring to two different vehicles. In my case the cars are called 'Ticky' and 'Miss Daisy'. Screenshot below of the two cars showing in the integration entries, but only one device. Also further below showing a dashboard for 'Car Miss Daisy' containing two different cabin temperatures for two different cars - but one is actually for Ticky...

Let me know if there is anything I can do to assist in troubleshooting this snag. Many thanks, Dave

![firefox_aTY0uFCZFg](https://github.com/jhansche/ha-teslafi/assets/42514569/af1c0599-c7bc-42ef-9ed4-dd2d0061c253)

![firefox_LG9Mund4t5](https://github.com/jhansche/ha-teslafi/assets/42514569/ba0f81ee-36f1-4b74-9e73-cd719c51d974)

**Comment by jhansche** [comment] 2023-09-28 00:50
Excellent info, thanks for reporting. I did try to make sure they would be associated with the correct devices, but I only have the one account, and it appears that maybe didn't work as expected.

I'll see what I can do to address that. Hopefully it's something obvious. If not I might ask for your help with some debug logs.

To clarify, are all of the entities working as expected, with data for the correct car, and only the device is mixing them together? And if you open the more info dialog for each entity, does it have the correct name for each car, as well as in the entity id? For example, `miss_daisy_car_state` and `ticky_car_state`? Or is each entity named for just one car, even though it should be for the second car?

**Comment by LampyDave** [comment] 2023-09-28 06:11
Thanks for getting back about this.
Yes the entities appear to be working as expected with the correct data. 
Taking cabin temperature as an example (because it's easy to differentiate the output), screenshots below which hopefully show the information you need - I'm new to HA.
The temperatures match what TeslaFi is reporting (Ticky @ 20.2, Miss Daisy @ 18.3).

![firefox_ZFwtnd4jDV](https://github.com/jhansche/ha-teslafi/assets/42514569/bc1b5bde-1a7c-4e3f-b882-0a0be103d864)

![firefox_7cd4Fdc4Ib](https://github.com/jhansche/ha-teslafi/assets/42514569/81364e06-fce1-4e18-9f15-e326b67ef1d8)

![firefox_UUSfYZt4Gu](https://github.com/jhansche/ha-teslafi/assets/42514569/e774ef34-2a50-4495-85aa-a8b169f6a5cb)

**Comment by jhansche** [comment] 2023-09-28 10:56
Great, thanks for confirming.

In that case the fix should be pretty simple 🤔

**Comment by jhansche** [comment] 2023-09-29 02:01
Are you comfortable viewing your `/config/.storage/core.device_registry` file?

Look for 2 entries containing:
```
"configuration_url": "https://www.teslafi.com/",
```

It's possible that there might only be one entry with that URL, since that would seem to line up with what you're seeing in the UI (one device, conflating the two physical cars as one).

Specifically, I'm curious about what the `identifiers[]` entry shows for each (you're welcome to redact the actual values). I'm more interested in whether it contains a value for `"tesla"` and/or `"teslafi"`, or it contains only `null` for those.

I used to get ids for those: `teslafi` should be the vehicle id in TeslaFi's database; and `tesla` should be the vehicle id from Tesla's API. But it appears that now I'm only seeing null for those from the teslafi API:
```
{ ...,
  "id": null,
  "vehicle_id": null,
  "vin": "5YJ...",
```

I think a fix for this would be to change how we're constructing `DeviceInfo.identifiers`. And since it seems we're getting the correct VIN from TeslaFi, that's probably the identifier we should use here.

However I'm not sure what effect that will have on the actual device registry and how those are currently being associated. That is: will it leave the old conflated device as an orphan; or will it split them apart as expected and keep them associated correctly. Or both. I may need to do some testing to see if I need to add a config entry version bump in order to do a one-time migration that removes the old device entry and adds the 2 new device entries.

I'll start by first switching a single device identifier, using `vin` as the id. Then we can test from there.  I'll let you know when I have something that can be tested, and how.

**Comment by jhansche** [comment] 2023-09-29 02:58
So, I thought we would be able to easily set up a way to test this before releasing, but it looks like HACS does not have that capability. I've opened a feature request to consider ways to facilitate end-user testing before a PR is merged.

Anyway, I'll let you know when there's an easier way to test.

**Comment by jhansche** [comment] 2023-09-29 03:34
I have a kind of hacky way to test it currently. First, go to the Integration > Device page that you showed in the screenshot originally, and make note of the URL: something like `http://<ha.local>/config/devices/device/<device_id>`, and specifically the `<device_id>`.

Go to HACS, find TeslaFi, and click the `⋮` icon on the right > `Redownload`:
![Screenshot 2023-09-28 at 11 03 32 PM](https://github.com/jhansche/ha-teslafi/assets/99272/90366499-a121-4491-956b-939a3a0cab8e)
On the next dialog, turn on "Show beta versions", and select `temp/pr/5` as the version to install, then click Download:
![Screenshot 2023-09-28 at 11 03 47 PM](https://github.com/jhansche/ha-teslafi/assets/99272/d69768d9-1fd6-47bb-be29-493ee406bb07)

Normal rules apply: it'll tell you a restart is required. After restarting, the TeslaFi integration will now show 3 devices - one is the original device (if you still have the URL open from above, just reload that URL). This original device *should* be blank now, and should show that there are no entities associated.
The other 2 should be the two new, unique devices, one per car. The entities listed for each device should be split correctly, with 40 entities on each device.

Assuming all of this tracks as I expect/hope, let me know so I at least know we're on the right track. If any of that _does not_ match expectations, please let me know.

I think there would be a way for me to manually clean up the old/bad orphaned device, but only if I do a config entry version bump and add a version migration so that when we migrate from v1 to v2, we would be able to delete the old orphaned device as part of the migration.

I'm not sure how much effort I want to put into it tbh, because from this point on it should continue to "Just Work", and it is possible to delete the orphaned device yourself, by clicking the `⋮` icon from the empty device page > `Delete`:

![Screenshot 2023-09-28 at 11 15 14 PM](https://github.com/jhansche/ha-teslafi/assets/99272/9b55fffb-875c-4688-a87b-2b99a7f929a6)

But the purist in me would want to clean that up so that we're not forcing other users to have to do the same.  Stay tuned.

**Comment by LampyDave** [comment] 2023-09-29 09:32
> Are you comfortable viewing your `/config/.storage/core.device_registry` file?
> 
> Look for 2 entries containing:
> 
> ```
> "configuration_url": "https://www.teslafi.com/",
> ```
> 
> It's possible that there might only be one entry with that URL, since that would seem to line up with what you're seeing in the UI (one device, conflating the two physical cars as one).
> 
> Specifically, I'm curious about what the `identifiers[]` entry shows for each (you're welcome to redact the actual values). I'm more interested in whether it contains a value for `"tesla"` and/or `"teslafi"`, or it contains only `null` for those.


Sorry for the delay - time zones... May be too late now, but have discovered how to view that file - below. It seems to be as you suspected.

      {
        "area_id": "car_miss_daisy",
        "config_entries": [
          "b96a...",
          "2f1c..."
        ],
        "configuration_url": "https://www.teslafi.com/",
        "connections": [],
        "disabled_by": null,
        "entry_type": null,
        "hw_version": "2022 Tesla",
        "id": "488f...",
        "identifiers": [
          [
            "vin",
            "LRW...51"
          ],
          [
            "tesla",
            null
          ],
          [
            "teslafi",
            null
          ],
          [
            "vin",
            "LRW...94"
          ]
        ],
        "manufacturer": "Tesla, Inc.",
        "model": null,
        "name_by_user": null,
        "name": "Miss Daisy",
        "sw_version": "2023.32.6 93d75c736e",
        "via_device_id": null
      },

**Comment by LampyDave** [comment] 2023-09-29 10:12
SO grateful for all your work with this. Re-downloaded the pr/5 as per, and I think it's almost what you're expecting. I suspect that it would now all be cleaned up and work brilliantly by removing the devices and re-adding them, but I haven't done that yet in case there's any information which you'd like before I do...

Now shows as 2 devices, but with the entities unevenly split:

![firefox_HlkrZpMeV0](https://github.com/jhansche/ha-teslafi/assets/42514569/5afa8e98-7209-452f-9f1e-bc17e69aae5c)

The original device ID is now unavailable, I don't know if that's the same as empty:

![firefox_YZoTvgIJOb](https://github.com/jhansche/ha-teslafi/assets/42514569/ff35abff-8c41-47c9-9dbd-d3ff4b9e15e7)

and the device_registry now has 4 search matches for 'TeslaFi' - was 2 before - but one of them has 2 VINs

![firefox_qFVJpCZAQF](https://github.com/jhansche/ha-teslafi/assets/42514569/c9644be9-2229-4f5c-8b10-83062231d3d9)

and

![firefox_fpocM0jUEi](https://github.com/jhansche/ha-teslafi/assets/42514569/38169889-9e10-424a-a8b3-6d2c825a2030)

the "config entries" are the same for both.

The sensors which are now showing as available have got a bit confused as well - the sensor.miss_daisy_car_state is now reporting Ticky's status. As I say I strongly suspect that this would / will be sorted out by removing and re-adding, but that perhaps doesn't help the rest of the user base! Conversely, with any luck the upgrade only goes wonky when there are 2 TeslaFi accounts linked - which is undoubtedly a **_much_** smaller user base!

I have a test RPi at work which I'm using to try things out on (new to HA but enthusiastic...) so I can try setting up the new integration with 2 TeslaFi accounts from scratch on a 'clean' system tomorrow.

Let me know if there's anything you'd like from the 'wonky' system - and thanks again! :)

**Comment by jhansche** [comment] 2023-09-29 15:17
OK, that is unexpected. It looks like it doesn't dedupe the VIN entry. I'll work on a config entry migration that will clean up the bad entries. Normally this would be done by mapping one-to-one config entries to devices, because all that's changing is the identifiers for known unique devices already, but in this case the device entries are known to be not (properly) unique.

That is, the devices that have 2 `config_entries` (`b96..` and `2f1..`) have now already conflated the two config entries into one device, so that definitely needs to be cleaned up. It should be one config entry, having one device entry, with 1 car's VIN, and 40 entities associated; and the 2nd config entry should be the same with one device, one VIN, and 40 entities, for the 2nd car. By this point it might be hard to identify which device to keep and which to remove.

I guess the easiest thing to do would be to (during the config flow migration, so it only happens once) delete all device entries for each config entry, and let HA recreate new devices on reload. But that will result in a new device.id. Doesn't actually matter here, because we don't have device actions/triggers/conditions, so it is still an option and the simplest option at this point.

If we want to keep the existing device ids, we would need to add a migration that, scans the device entries for each config entry, and tries to "normalize" them by:
1. ensure only one config entry is associated with each device (so splitting the `config_entries` items in your last 2 screenshots)
2. ensure only one device is associated with each config entry (not quite as straightforward, because the device gets associated with the config entry using that array from (1))
3. ensure each device entry contains only one identifier (the `teslafi=$vin` entry), and remove any duplicates or extraneous entries

That's a lot of effort to go through, and probably not worth it. I think for now I'll just make it delete all device entries on migration, and let HA recreate them.

**Comment by LampyDave** [comment] 2023-09-29 16:46
Agreed - given that the Venn diagram overlap between 'Uses HA' and 'Is interested in 2 different TeslaFi accounts' is probably pretty slim it feels like it wouldn't be worth the considerable effort involved!

**Comment by jhansche** [comment] 2023-09-29 18:29
OK, can you try redownloading the temp tag again?

In HACS, first click `⋮` > `Update information`, then `⋮` > `Redownload` and select the temp/pr/5 tag again, then restart HA.

It should:
* clear identifiers for all current device entries
* clear config entries for those device entries
* finally delete the device entry

You should see a warning entry in the System > Logs, explaining that it is removing a corrupted device (in your case you may see it log 4x). From there, it should proceed with setting up the integration with the correct device identifiers, and you should then finally have 2 devices with 40 entities each.

**Comment by LampyDave** [comment] 2023-09-30 14:46
Sadly not - it now ends up with 40 entities (all .miss_daisy) - for instance sensor.miss_daisy_battery, but split between the two devices (Ticky and Miss Daisy). Let me know if you'd like any other info, but it feels like that part has taken up enough of your time.
On a happier note, I have now tried pr/5 on the clean system, setting it up from scratch with the two vehicles and it appears to be perfect - 2 devices each with 40 entities. So that appears to be excellent :) Again, let me know if you'd like any diagnostic info from that system.

**Comment by jhansche** [comment] 2023-09-30 16:26
Does that mean that the other 40 for Ticky just disappeared? 

In the device registry file, other than the "HACS" entry for the integration repo, how many other devices are there with the domain "teslafi"? And how many identifiers for each? There may also be some that got moved to the deleted/orphaned section towards the end of the file, which is what I expected to happen: I expected it to move all of the associated devices to deleted, and then when loading the integration, it should have created 40 and 40, each with their respective (new) device.

What might have happened though, since I was only testing the migration with my one config entry because I don't have a second API key, is it might have gone through the whole process twice: load car one, migrate car one (which should have deleted any matching devices), add entities and new device for car one; and then do the same steps for car 2. But the migration for car one should have cleared all of the related entities, identifiers, and config entries for car one, which should have severed any connections to car two before it even got to that point...

I'm worried about the fact that you lost all of the car two entities. That's the most troubling part.

**Comment by LampyDave** [comment] 2023-09-30 16:50
Yes the others seem to have vanished.

2 instances of 'teslafi' in the core.device_registry file:

{
        "area_id": "garage_stereo",
        "config_entries": [
          "b96a...1b21",
          "2f1c...0e84"
        ],
        "configuration_url": "https://www.teslafi.com/",
        "connections": [],
        "disabled_by": null,
        "entry_type": null,
        "hw_version": "2022 Tesla",
        "id": "4d057...331bc",
        "identifiers": [
          [
            "teslafi",
            "LRW...494"
          ]
        ],
        "manufacturer": "Tesla, Inc.",
        "model": null,
        "name_by_user": null,
        "name": "Miss Daisy",
        "sw_version": "2023.32.6 93d75c736e",
        "via_device_id": null
      },

**Comment by jhansche** [comment] 2023-09-30 17:42
Ok, and again the double config entry is unexpected. That means that both entries are association themselves with the one device.

Also odd that it lists both config entries, but you don't have the second car's entities?

I'll run some more tests and see if I can figure out what's happening

**Comment by LampyDave** [comment] 2023-09-30 17:54
Okey dokey. 
I don't feel that I can share my API keys so you can test locally, but if you'd like me to remove everything, revert back to the release version, add the 2 accounts again (so that there are 80 entities under 1 device) and then go through the pr/5 process again I'm very happy to do that. 

I won't do that unless you say though - in case you want to try something else from where my system currently is. However, because my system has done the two different versions of pr/5 I thought maybe mine is now in a weird state!

**Comment by jhansche** [comment] 2023-09-30 18:47
No worries, I don't need your token.

Anyway, given that you're probably one out of a tiny handful who may be in this situation (I don't even know how many people have found the integration at all, and it was never advertised in the forum or anything), and you're seeing that it comes up correctly on a clean installation with the pr/5 version, I think I'm going to call it good enough for now, and just call it out in the release notes.

So, just one last test: let's try removing the integration on the broken one, redownload pr/5 from HACS, and then add back the integration (x2). Hopefully it will come up like it did on your fresh install, and if so, I'll release it like that. If not, and it's in a broken/half state, we may need to do some more work to clean up the broken device entries.

**Comment by LampyDave** [comment] 2023-09-30 18:58
Yep absolutely. Have just done that and it appears to be perfect (thanks again). Device registry is now as below - and everything appears to be brilliant. Your work on this is hugely appreciated!

{
        "area_id": "car_ticky",
        "config_entries": [
          "d77b...0dc7"
        ],
        "configuration_url": "https://www.teslafi.com/",
        "connections": [],
        "disabled_by": null,
        "entry_type": null,
        "hw_version": "2023 Tesla",
        "id": "78fee...3048",
        "identifiers": [
          [
            "teslafi",
            "LRW...351"
          ]
        ],
        "manufacturer": "Tesla, Inc.",
        "model": null,
        "name_by_user": null,
        "name": "Ticky",
        "sw_version": "2023.32.6 93d75c736e",
        "via_device_id": null
      },
      {
        "area_id": "car_miss_daisy",
        "config_entries": [
          "e4eb...daeb2"
        ],
        "configuration_url": "https://www.teslafi.com/",
        "connections": [],
        "disabled_by": null,
        "entry_type": null,
        "hw_version": "2022 Tesla",
        "id": "4d0...0331bc",
        "identifiers": [
          [
            "teslafi",
            "LRW...494"
          ]
        ],
        "manufacturer": "Tesla, Inc.",
        "model": null,
        "name_by_user": null,
        "name": "Miss Daisy",
        "sw_version": "2023.32.6 93d75c736e",
        "via_device_id": null
      }

**Comment by jhansche** [comment] 2023-09-30 19:03
OK great, thanks for checking.

And just to confirm - this was on the initial broken install, not the sandbox/pi clean system that you tested [here](https://github.com/jhansche/ha-teslafi/issues/4#issuecomment-1741781746)?

I'm just going to do one more round of cleanup, because I think I can make the device entry migration smarter (so it doesn't have to delete a device if all it needs to do is rearrange the identifiers). But since you've already applied the migration now (config flow v2), once it does get re-released, it won't affect you because your config version will match, and it won't try to migrate you again.

**Comment by LampyDave** [comment] 2023-09-30 19:05
Yes, this was on my main install which had been 'wonky' before.
:)

**Comment by jhansche** [comment] 2023-09-30 19:26
OK, confirmed that migrating config entry v1 to v2 works correctly and does not have to delete the device (which can be problematic since it also resets entity overrides - such as if you've enabled one of the disabled-by-default entities).

Now going from v1 to (future) v2, as long as it's not in a broken state like yours was, it will just rewrite the identifiers and not delete anything else.

I'm going to close this with the #5 PR

**Comment by jhansche** [comment] 2023-09-30 19:44
`v2.0` is now released. HACS should prompt to install it (or you can force it in HACS with `⋮` > `Update information`, and then install it from the `update` entity - no need to "Redownload" again).

Also, side note, I did speak with the maintainer of HACS, and he says he is planning to make it possible to install an arbitrary version in the future, using the `update.install` service (right now it's not supported to install a specified version, but that will be coming in v2.0 of HACS). That will make it possible (easier) to install one-off test branches, instead of the `temp/pr/5` tag I had to use for this.

**Comment by LampyDave** [comment] 2023-10-21 22:02
Hello again :)
I fear this may not be very welcome news, and I apologise for the delay reporting it - it has been a bit of a few weeks. It seems that something is going squiffy with the '2 account' settings upon HA restart. I toyed with not reporting it (because it probably only affects me in any case) but thought it might be something simple. So to try and get some relevant information in one place...

Removed both TeslaFi accounts. Linked first TeslaFi account (Ticky) to HA. All added fine. core.device_registry entry now:

![ACDSeeQVUltimate13_t2QfEWy2b5](https://github.com/jhansche/ha-teslafi/assets/42514569/8865da68-e085-4711-b4d8-8e323e2f261b)

re-started HA. All still working and registry unchanged. Linked the second (Miss Daisy) account to HA. Linked fine, both show up (and show the correct information) in the Overview.  core.device_registry entry now:

![firefox_ozKUMiFt6a](https://github.com/jhansche/ha-teslafi/assets/42514569/92693d02-c878-474e-806b-e4e37768ec11)

Also no 'TeslaFi' entries in the log. All is well. Then restarted HA again...

Ticky has now become 'unavailable' and there are several entries in the log about unique IDs

![firefox_ElttI1bjz4](https://github.com/jhansche/ha-teslafi/assets/42514569/8669bc50-2cb1-476b-a03c-97280087bc89)

and the config_entries in the registry file have got 'mixed'

![firefox_6wdQxrSWyI](https://github.com/jhansche/ha-teslafi/assets/42514569/6a765bb9-073c-46d2-8cf6-ebd974c8c273)

As before, if this is something that can be fixed without taking up lots of your time then that would be great, but I am already very grateful for your work on this and don't expect anything!

**Comment by jhansche** [comment] 2023-10-22 07:16
It sounds like the `unique_id` is causing it to get mixed up now. The `unique_id` is derived from the VIN, but it sounds like it thinks that that id already exists, but provided by another config entry. It's possible that the unique id didn't get cleaned up from the first time it all got mixed up.

Did you still have that 2nd "sandbox" server you were toying with previously? And are both cars still connected and working fine there, including after a restart? If the 2nd server is still working correctly, I think that means that the current integration is correct, but the devices/entities (and unique ids) from the broken version a few weeks ago are still lingering somewhere and causing problems.

But I don't have a good way to test this scenario, since I only have one car and one TeslaFi account.

**Comment by LampyDave** [comment] 2023-10-22 08:29
Makes sense. I do still have the sandbox server and the behaviour is the same on that one (breaks after a restart), but that may also have some IDs left over from the previous iteration. There's nothing on that server that I need day to day so I'll take a backup of it, wipe it clean and then start from a properly clean install to see where we're at :)

**Comment by BDubz20** [comment] 2023-11-07 19:22
Also seeing this behavior with two Tesla vehicles. Tested via clean instance of HA, works until rebooting core and then the second Tesla goes unavailable.  Any thoughts on what can be causing this.  Would be happy to provide a token to help troubleshoot and get this great integration to support >1 vehicle.  Thanks!

**Comment by jhansche** [comment] 2023-11-07 20:32
If you're willing to provide a teslafi token, that would help me with testing. I may also be able to mock a 2nd device, in which case I may not need a real teslafi token.

But I'm transitioning to a new workstation right now and I'm not quite at a point where I can work on it, and it wouldn't make sense to provide me access until I can actually sit down and work on it. I might have some time later in the week or this weekend, but I'll give you a heads up so that you can prepare a temporary token for testing; and a timeframe so you can know when it's clear to revoke/regenerate.

**Comment by BDubz20** [comment] 2023-11-07 21:00
Happy to provide @jhansche  when you're ready to troubleshoot.  Really appreciate it.  Happy to support in anyway as this is a very useful repo, something I had been using template sensors and JSON parsing prior.

**Comment by BDubz20** [comment] 2023-11-18 17:21
Sorry to bother, but have you had any luck figuring it out? Would provide a second token if you needed.  Thank you

**Comment by LampyDave** [comment] 2023-11-19 21:37
Just as a data point, I tried manually installing the integration to a different folder in custom_components and changing the domain information in manifest.json and const.py. Then that second 'copy' of the integration had the second API key. It sort-of worked as in each integration retained 40 entities after a restart, but a range of sensors (battery, range, cabin and outside temperatures) became unavailable on both cars / accounts. 
I have since removed the second copy and re-started, and the information for the one car / account has come back fine. I had to revert because W.A.F. (Wife Approval Factor) would reduce rapidly if her car wasn't warm...!

**Comment by jhansche** [comment] 2023-11-25 01:27
I finally got some time to look into this. I was able to reproduce the issue on my own, by mocking a 2nd vehicle - but thank you for the offer to use your token @BDubz20.

The issue ended up being a memory leak caused by using shared state between the two config entries, leading to data corruption between the two entries: entities from one device start bleeding over into the other device, and vice versa.

This also led to finding some other issues: for example, we weren't defining a proper `ConfigEntry.unique_id`. I believe this is caused by the same issue that led to this issue in the first place: TeslaFi _used_ to report 3 identifier fields (`vin`, `id`, and `vehicle_id`). But now they only return the `vin`, not the teslafi and tesla ids. We were using `id` for the unique_id, and now that results in `unique_id=None` for all config entries. Normally that's not a big deal, when there's only one config entry. But it becomes a big(ger) deal when you try to add more than one entry.  I'll also be resolving that, with a config flow schema migration.

Thanks for your patience, both of you. I'll let you know when the fix has been released.

**Closed** 2023-11-25 01:38 UTC

**Comment by jhansche** [comment] 2023-11-25 02:01
For this particular issue -- and I would recommend checking here first before you update, just so you can see what has changed -- when you go Settings > Integrations > TeslaFi (http://hass.local:8123/config/integrations/integration/teslafi), you will likely see something like this:

![Screenshot 2023-11-24 at 8 49 33 PM](https://github.com/jhansche/ha-teslafi/assets/99272/e519036c-25a8-4668-80a6-f7233807cd54)

that is, this is what we *want* to see, and the first time you add the 2nd API key, this is what you _should_ see. Even after reloading config entries, this continues to look correct. Specifically, each entry should have `1 device, 40 entities`.

But as soon as you restart Home Assistant, things get weird. For one or both physical device entries (cars), some of the entities will get mixed in with the other physical device. For one or both config entries, you'll see `2 devices, {N} entities` for one, and `1 device, {80-N} entities` for the other. There are other variations that might come up as well, but they're all wrong :) 

After the update, you'll know that it is *fixed*, if you see `40 entities` for each entry -- BUT you might still see `2 devices` for one or both. This is unexpected, but should no longer happen after the fix.

I do not know what kind of side effects you might experience if you leave it like this - but you're welcome to try leaving it if you want to see what happens.

If it bothers you (like it would me), you can clear that count by deleting the old device(s) that have gotten mixed up. The above screen would tell you if a config entry is associated with more than one device (`2 devices, 40 entities`). But what you want to see is which device is associated with more than one config entry -- yes, it can go both ways. Do that by clicking on the `2 devices`, and it'll take you to the filtered device list. Under the "Integration" column, you might see the integration listed twice: `TeslaFi, TeslaFi` - open that device. Then through the overflow menu, delete the device entry:
![Screenshot 2023-11-24 at 8 55 09 PM](https://github.com/jhansche/ha-teslafi/assets/99272/005a6a96-25f2-47a0-a1de-dab0a9920087)

Once that's done, you'll want to go back to the Integration page, and reload both config entries. Once it's reloaded, you'll see just `1 device, 40 entities` for both, and you'll be able to restart HA and they won't get mixed up anymore.

**Comment by jhansche** [comment] 2023-11-25 02:05
The update is available now: [`v2.1`](https://github.com/jhansche/ha-teslafi/releases/tag/v2.1)

**Comment by BDubz20** [comment] 2023-11-25 07:13
Amazing @jhansche.  Thanks for all the hard work and for fixing the bug.  Looking forward to getting the automations running again.  How can I support you and this repo?  Happy to buy you a coffee :)

**Comment by jhansche** [comment] 2023-11-26 05:20
Pay it forward 😁☕

**Comment by LampyDave** [comment] 2023-11-27 07:57
Just to add my thanks again for the work on this - seems to be working beautifully on two accounts now. Now it's not just my wife that can have a car warmed up by an automation in the mornings :)
